#![allow(dead_code)]
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(info(title="Agent Web API",version="0.1.0",description="Agent Web backend API. Protected endpoints require the Agent Web session cookie."),tags((name="System",description="System health"),(name="Auth",description="Authentication and account security"),(name="Agents",description="Agent catalog, installation and configuration"),(name="Models",description="Model discovery and selection"),(name="Runtime",description="Node.js and Agent runtime"),(name="Sessions",description="Coding session lifecycle"),(name="Messages",description="Session messages and Agent execution"),(name="Workspace",description="Workspace files and Git diff"),(name="Events",description="Real-time session events")),paths(health,auth_login,auth_me,auth_logout,auth_password,auth_sessions,auth_revoke_all,agents_get,agents_post,agent_catalog,runtime_settings_get,runtime_settings_put,node_versions,node_install,agent_status,agent_models,agent_config_get,agent_config_put,agent_install,agent_custom_install,filesystem_tree,sessions_get,sessions_post,session_get,session_delete,session_title,session_pin,session_model,session_messages_get,session_messages_post,session_interrupt,session_files,session_file,session_diff,session_events))]
pub struct ApiDoc;

#[utoipa::path(get,path="/api/health",tag="System",summary="Health check",description="Returns successfully when the backend is running.",responses((status=200,description="Backend is healthy")))]fn health(){}
#[utoipa::path(post,path="/api/auth/login",tag="Auth",summary="Login",description="Authenticates the user and creates a persistent session cookie. Three failed attempts lock the IP for 30 minutes.",request_body=serde_json::Value,responses((status=200,description="Login succeeded"),(status=401,description="Invalid credentials"),(status=429,description="IP temporarily locked")))]fn auth_login(){}
#[utoipa::path(get,path="/api/auth/me",tag="Auth",summary="Current account",description="Returns the authenticated username and current session id.",responses((status=200,description="Account information"),(status=401,description="Not authenticated")))]fn auth_me(){}
#[utoipa::path(post,path="/api/auth/logout",tag="Auth",summary="Logout",description="Revokes the current login session and clears its cookie.",responses((status=200,description="Logged out")))]fn auth_logout(){}
#[utoipa::path(put,path="/api/auth/password",tag="Auth",summary="Change password",description="Changes the password and revokes all other active sessions.",request_body=serde_json::Value,responses((status=200,description="Password changed"),(status=400,description="Invalid password"),(status=401,description="Not authenticated")))]fn auth_password(){}
#[utoipa::path(get,path="/api/auth/sessions",tag="Auth",summary="List login sessions",description="Lists active sessions and marks the current session.",responses((status=200,description="Active sessions"),(status=401,description="Not authenticated")))]fn auth_sessions(){}
#[utoipa::path(post,path="/api/auth/sessions/revoke-all",tag="Auth",summary="Revoke other sessions",description="Keeps the current session and revokes every other session.",responses((status=200,description="Other sessions revoked"),(status=401,description="Not authenticated")))]fn auth_revoke_all(){}
#[utoipa::path(get,path="/api/agents",tag="Agents",summary="List Agents",description="Returns configured Agents and installation state.",responses((status=200,description="Agent list")))]fn agents_get(){}
#[utoipa::path(post,path="/api/agents",tag="Agents",summary="Create Agent",description="Registers a custom Agent definition.",request_body=serde_json::Value,responses((status=200,description="Agent created"),(status=400,description="Invalid definition")))]fn agents_post(){}
#[utoipa::path(get,path="/api/agent-catalog",tag="Agents",summary="Agent catalog",description="Returns popular Agents and one-click installation commands.",responses((status=200,description="Agent catalog")))]fn agent_catalog(){}
#[utoipa::path(get,path="/api/runtime/settings",tag="Runtime",summary="Get runtime settings",description="Returns Node.js and per-Agent executable paths.",responses((status=200,description="Runtime settings")))]fn runtime_settings_get(){}
#[utoipa::path(put,path="/api/runtime/settings",tag="Runtime",summary="Update runtime settings",description="Stores Node.js and independent Agent executable paths.",request_body=serde_json::Value,responses((status=200,description="Settings updated"),(status=400,description="Invalid settings")))]fn runtime_settings_put(){}
#[utoipa::path(get,path="/api/node/versions",tag="Runtime",summary="List Node versions",description="Returns Node.js releases available to the installer.",responses((status=200,description="Node versions")))]fn node_versions(){}
#[utoipa::path(post,path="/api/node/install",tag="Runtime",summary="Install Node",description="Installs an exact Node.js version or the newest available release matching a major version such as 22.",request_body=serde_json::Value,responses((status=200,description="Installed"),(status=400,description="Installation failed")))]fn node_install(){}
#[utoipa::path(post,path="/api/agents/custom/install",tag="Agents",summary="Run custom Agent install command",description="Runs a user-provided shell installation command inside the Agent Web container. This is intended for personal Docker deployments.",request_body=serde_json::Value,responses((status=200,description="Command completed"),(status=400,description="Command failed")))]fn agent_custom_install(){}
#[utoipa::path(get,path="/api/agents/{id}/status",tag="Agents",summary="Agent status",description="Checks whether an Agent executable is available and reports its version.",params(("id"=String,Path)),responses((status=200,description="Agent status"),(status=404,description="Agent not found")))]fn agent_status(){}
#[utoipa::path(get,path="/api/agents/{id}/models",tag="Models",summary="List Agent models",description="Discovers models using the selected Agent's own model configuration. Codex and Pi are currently supported.",params(("id"=String,Path)),responses((status=200,description="Model list"),(status=404,description="Agent not found")))]fn agent_models(){}
#[utoipa::path(get,path="/api/agents/{id}/config",tag="Agents",summary="Read Agent native configuration",description="Returns the native configuration file. Codex and Pi have known default locations; other Agents expose suggested locations and allow a custom path under HOME.",params(("id"=String,Path),("path"=Option<String>,Query)),responses((status=200,description="Agent configuration"),(status=404,description="Agent not found")))]fn agent_config_get(){}
#[utoipa::path(put,path="/api/agents/{id}/config",tag="Agents",summary="Save Agent native configuration",description="Writes a native Agent configuration file under HOME. The path is restricted to HOME and limited to 1 MiB.",params(("id"=String,Path)),request_body=serde_json::Value,responses((status=200,description="Configuration saved"),(status=400,description="Invalid path or configuration"),(status=404,description="Agent not found")))]fn agent_config_put(){}
#[utoipa::path(post,path="/api/agents/{id}/install",tag="Agents",summary="Install Agent",description="Starts installation of the selected Agent runtime.",params(("id"=String,Path)),responses((status=200,description="Installation started"),(status=404,description="Unknown Agent")))]fn agent_install(){}
#[utoipa::path(get,path="/api/sessions/{id}/filesystem/tree",tag="Workspace",summary="List session workspace filesystem",description="Lists files and directories under the current session workspace. Use path for one-level browsing or search for a case-insensitive recursive name/path search.",params(("id"=String,Path,description="Session ID"),("path"=Option<String>,Query,description="Relative directory path inside the session workspace"),("search"=Option<String>,Query,description="Case-insensitive recursive search across the session workspace; ignored directories such as .git, node_modules and target are skipped")),responses((status=200,description="Filesystem tree or search results"),(status=400,description="Invalid path or path is not a directory"),(status=403,description="Path is outside the session workspace"),(status=404,description="Session or path not found")))]fn filesystem_tree(){}
#[utoipa::path(get,path="/api/sessions",tag="Sessions",summary="List sessions",description="Returns sessions ordered by most recent update.",responses((status=200,description="Session list")))]fn sessions_get(){}
#[utoipa::path(post,path="/api/sessions",tag="Sessions",summary="Create session",description="Creates a session and its workspace.",request_body=serde_json::Value,responses((status=200,description="Session created"),(status=400,description="Invalid workspace"),(status=404,description="Agent not found")))]fn sessions_post(){}
#[utoipa::path(get,path="/api/sessions/{id}",tag="Sessions",summary="Get session",description="Returns session metadata, selected Agent and model.",params(("id"=String,Path)),responses((status=200,description="Session"),(status=404,description="Session not found")))]fn session_get(){}
#[utoipa::path(delete,path="/api/sessions/{id}",tag="Sessions",summary="Delete session",description="Stops a running Agent and deletes the session record without deleting the shared workspace.",params(("id"=String,Path)),responses((status=204,description="Deleted"),(status=404,description="Session not found")))]fn session_delete(){}
#[utoipa::path(put,path="/api/sessions/{id}/title",tag="Sessions",summary="Rename session",description="Changes the sidebar title of a session.",params(("id"=String,Path)),request_body=serde_json::Value,responses((status=200,description="Session renamed"),(status=404,description="Session not found")))]fn session_title(){}
#[utoipa::path(put,path="/api/sessions/{id}/pin",tag="Sessions",summary="Toggle session pin",description="Pins or unpins a session in the sidebar.",params(("id"=String,Path)),responses((status=200,description="Pin state updated"),(status=404,description="Session not found")))]fn session_pin(){}
#[utoipa::path(put,path="/api/sessions/{id}/model",tag="Models",summary="Set session model",description="Changes the model while the session is idle.",params(("id"=String,Path)),request_body=serde_json::Value,responses((status=200,description="Model updated"),(status=409,description="Session is running")))]fn session_model(){}
#[utoipa::path(get,path="/api/sessions/{id}/messages",tag="Messages",summary="List messages",description="Returns persisted messages in chronological order.",params(("id"=String,Path)),responses((status=200,description="Messages"),(status=404,description="Session not found")))]fn session_messages_get(){}
#[utoipa::path(post,path="/api/sessions/{id}/messages",tag="Messages",summary="Send message",description="Starts an asynchronous Agent run for the session.",params(("id"=String,Path)),request_body=serde_json::Value,responses((status=200,description="Run started"),(status=409,description="Session is already running")))]fn session_messages_post(){}
#[utoipa::path(post,path="/api/sessions/{id}/interrupt",tag="Sessions",summary="Interrupt session",description="Requests termination of the running Agent process.",params(("id"=String,Path)),responses((status=200,description="Interrupt requested"),(status=502,description="Interrupt failed")))]fn session_interrupt(){}
#[utoipa::path(get,path="/api/sessions/{id}/files",tag="Workspace",summary="List workspace files",description="Returns workspace files with Git status information.",params(("id"=String,Path)),responses((status=200,description="File tree"),(status=404,description="Workspace not found")))]fn session_files(){}
#[utoipa::path(get,path="/api/sessions/{id}/file/{path}",tag="Workspace",summary="Preview file",description="Returns text contents up to the preview limit; deleted files may be read from Git HEAD.",params(("id"=String,Path),("path"=String,Path)),responses((status=200,description="File preview"),(status=400,description="Invalid path"),(status=404,description="File not found")))]fn session_file(){}
#[utoipa::path(get,path="/api/sessions/{id}/diff",tag="Workspace",summary="Get diff",description="Returns the workspace Git diff including supported untracked text files.",params(("id"=String,Path)),responses((status=200,description="Git diff"),(status=502,description="Git command failed")))]fn session_diff(){}
#[utoipa::path(get,path="/api/sessions/{id}/events",tag="Events",summary="Session events",description="WebSocket endpoint streaming Agent, message, tool, command and file events for a session.",params(("id"=String,Path)),responses((status=101,description="WebSocket upgrade"),(status=404,description="Session not found")))]fn session_events(){}