use crate::state::AppState;
use axum::{extract::{Path, State}, http::StatusCode, Json};
use chrono::Utc;
use serde::{Deserialize, Serialize};
use sqlx::Row;
use std::path::{Component, Path as FsPath};
use tokio::fs;
use uuid::Uuid;

#[derive(Serialize, Clone)]
pub struct Session { pub id:String, pub agent_id:String, pub title:String, pub workspace:String, pub status:String, pub native_session_id:Option<String>, pub model:Option<String>, pub is_pinned:bool }
fn session_from_row(row:&sqlx::sqlite::SqliteRow)->Session { Session{id:row.get(0),agent_id:row.get(1),title:row.get(2),workspace:row.get(3),status:row.get(4),native_session_id:row.get(5),model:row.get(6),is_pinned:row.get::<i64,_>(7)!=0} }
pub(crate) async fn load_session(db:&sqlx::SqlitePool,id:&str)->Result<Session,StatusCode>{let row=sqlx::query("SELECT id,agent_id,title,workspace,status,native_session_id,model,is_pinned FROM sessions WHERE id=?").bind(id).fetch_optional(db).await.map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?.ok_or(StatusCode::NOT_FOUND)?;let mut session=session_from_row(&row);let base_path=std::env::var("AGENTWEB_WORKSPACE_DIR").unwrap_or_else(|_|"./data/workspaces".into());if let (Ok(base),Ok(workspace))=(fs::canonicalize(base_path).await,fs::canonicalize(&session.workspace).await){let legacy=base.join(id);if workspace==legacy{session.workspace=base.to_string_lossy().into_owned();let _=sqlx::query("UPDATE sessions SET workspace=?,updated_at=? WHERE id=?").bind(&session.workspace).bind(Utc::now().to_rfc3339()).bind(id).execute(db).await;}}Ok(session)}
pub async fn list_sessions(State(s):State<AppState>)->Json<Vec<Session>>{let rows=sqlx::query("SELECT id,agent_id,title,workspace,status,native_session_id,model,is_pinned FROM sessions ORDER BY is_pinned DESC, updated_at DESC").fetch_all(&s.db).await.unwrap_or_default();Json(rows.iter().map(session_from_row).collect())}
#[derive(Deserialize)] pub struct CreateSession { pub agent_id:Option<String>,pub title:Option<String>,pub workspace:Option<String>,pub model:Option<String> }
async fn resolve_workspace(requested:Option<&str>)->Result<String,StatusCode>{let base_path=std::env::var("AGENTWEB_WORKSPACE_DIR").unwrap_or_else(|_|"$HOME/.local/share/agentweb/workspaces".into());fs::create_dir_all(&base_path).await.map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?;let base=fs::canonicalize(&base_path).await.map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?;let name=requested.unwrap_or("").trim();let path=FsPath::new(name);if name.is_empty()||name=="."{return Ok(base.to_string_lossy().into_owned())}if path.is_absolute()||path.components().any(|c|matches!(c,Component::ParentDir)){return Err(StatusCode::BAD_REQUEST)}let workspace=base.join(path);fs::create_dir_all(&workspace).await.map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?;let canonical=fs::canonicalize(&workspace).await.map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?;if !canonical.starts_with(&base){return Err(StatusCode::FORBIDDEN)}Ok(canonical.to_string_lossy().into_owned())}
pub async fn create_session(State(s):State<AppState>,Json(v):Json<CreateSession>)->Result<Json<Session>,StatusCode>{let agent_id=match v.agent_id.filter(|v|!v.trim().is_empty()){Some(id)=>id,None=>crate::api::runtime::setting(&s.db,"default_agent_id").await.filter(|v|!v.trim().is_empty()).ok_or(StatusCode::BAD_REQUEST)?};crate::api::runtime::build_agent_config(&s.db,&agent_id).await.map_err(|_|StatusCode::BAD_REQUEST)?;let model=match v.model{Some(model)=>Some(model.trim().to_owned()).filter(|m|!m.is_empty()),None=>crate::api::runtime::setting(&s.db,"default_model").await.filter(|v|!v.trim().is_empty())};let id=Uuid::new_v4().to_string();let workspace=resolve_workspace(v.workspace.as_deref()).await?;let now=Utc::now().to_rfc3339();let title=v.title.filter(|t|!t.trim().is_empty()).unwrap_or_else(||"New Chat".into());sqlx::query("INSERT INTO sessions(id,agent_id,title,workspace,status,native_session_id,model,is_pinned,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(&id).bind(&agent_id).bind(&title).bind(&workspace).bind("idle").bind::<Option<String>>(None).bind(&model).bind(0i64).bind(&now).bind(&now).execute(&s.db).await.map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?;Ok(Json(Session{id,agent_id,title,workspace,status:"idle".into(),native_session_id:None,model,is_pinned:false}))}
#[derive(Deserialize)] pub struct RenameSession { pub title:String }
pub async fn rename_session(Path(id):Path<String>,State(s):State<AppState>,Json(v):Json<RenameSession>)->Result<Json<Session>,StatusCode>{let title=v.title.split_whitespace().collect::<Vec<_>>().join(" ");if title.is_empty(){return Err(StatusCode::BAD_REQUEST)}let title=title.chars().take(80).collect::<String>();load_session(&s.db,&id).await?;sqlx::query("UPDATE sessions SET title=?,updated_at=? WHERE id=?").bind(&title).bind(Utc::now().to_rfc3339()).bind(&id).execute(&s.db).await.map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?;Ok(Json(load_session(&s.db,&id).await?))}
pub async fn toggle_pin(Path(id):Path<String>,State(s):State<AppState>)->Result<Json<Session>,StatusCode>{load_session(&s.db,&id).await?;sqlx::query("UPDATE sessions SET is_pinned=CASE WHEN is_pinned=1 THEN 0 ELSE 1 END,updated_at=? WHERE id=?").bind(Utc::now().to_rfc3339()).bind(&id).execute(&s.db).await.map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?;Ok(Json(load_session(&s.db,&id).await?))}
pub async fn get_session(Path(id):Path<String>,State(s):State<AppState>)->Result<Json<Session>,StatusCode>{Ok(Json(load_session(&s.db,&id).await?))}
pub async fn delete_session(Path(id):Path<String>,State(s):State<AppState>)->StatusCode{let session=match load_session(&s.db,&id).await{Ok(v)=>v,Err(e)=>return e};if session.status=="running"{let _=s.agents.interrupt(&id).await;}match sqlx::query("DELETE FROM sessions WHERE id=?").bind(&id).execute(&s.db).await{Ok(r) if r.rows_affected()==1=>StatusCode::NO_CONTENT,Ok(_)=>StatusCode::NOT_FOUND,Err(_)=>StatusCode::INTERNAL_SERVER_ERROR}}
#[derive(Deserialize)] pub struct SetModel { pub model:Option<String> }
pub async fn set_session_model(Path(id):Path<String>,State(s):State<AppState>,Json(v):Json<SetModel>)->Result<Json<Session>,StatusCode>{let session=load_session(&s.db,&id).await?;if session.status=="running"{return Err(StatusCode::CONFLICT)}sqlx::query("UPDATE sessions SET model=?,updated_at=? WHERE id=?").bind(&v.model).bind(Utc::now().to_rfc3339()).bind(&id).execute(&s.db).await.map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?;Ok(Json(load_session(&s.db,&id).await?))}
#[derive(Deserialize)] pub struct SetAgent { pub agent_id:String }
pub async fn set_session_agent(Path(id):Path<String>,State(s):State<AppState>,Json(v):Json<SetAgent>)->Result<Json<Session>,StatusCode>{let session=load_session(&s.db,&id).await?;if session.status=="running"{return Err(StatusCode::CONFLICT)}let agent_id=v.agent_id.trim();if agent_id.is_empty(){return Err(StatusCode::BAD_REQUEST)}crate::api::runtime::build_agent_config(&s.db,agent_id).await.map_err(|_|StatusCode::BAD_REQUEST)?;sqlx::query("UPDATE sessions SET agent_id=?,model=NULL,updated_at=? WHERE id=?").bind(agent_id).bind(Utc::now().to_rfc3339()).bind(&id).execute(&s.db).await.map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?;Ok(Json(load_session(&s.db,&id).await?))}
