import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{MessageCircle,Plus,Settings,Square,Send as SendIcon}from'lucide-react';import'./style.css';
type Agent={id:string,name:string,description?:string,installed:boolean,requirements:string[]};type Session={id:string,agent_id:string,title:string,workspace:string,status:string};type ChatMessage={id:string,role:string,content:string};
const api=(p:string,o?:RequestInit)=>fetch('/api'+p,{headers:{'Content-Type':'application/json'},...o}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'request failed');return d});
function App(){const[agents,setAgents]=useState<Agent[]>([]),[sessions,setSessions]=useState<Session[]>([]),[active,setActive]=useState<string>(),[input,setInput]=useState(''),[messages,setMessages]=useState<ChatMessage[]>([]),[catalog,setCatalog]=useState(false),[running,setRunning]=useState(false),[installing,setInstalling]=useState<string>();
useEffect(()=>{api('/agent-catalog').then(setAgents);api('/sessions').then(setSessions)},[]);
useEffect(()=>{if(!active)return;setMessages([]);api(`/sessions/${active}/messages`).then((m:ChatMessage[])=>setMessages(m));const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/sessions/${active}/events`);ws.onmessage=e=>{const ev=JSON.parse(e.data);if(ev.type==='session.started'||ev.type==='message.started')setRunning(true);if(ev.type==='message.delta')setMessages(x=>{const last=x[x.length-1];if(last?.role==='assistant')return[...x,{...last,content:last.content+ev.data.text}];return[...x,{id:'stream',role:'assistant',content:ev.data.text}]});if(ev.type==='message.completed'||ev.type==='session.completed'||ev.type==='agent.error'){setRunning(false);if(ev.type==='agent.error')setMessages(x=>[...x,{id:crypto.randomUUID(),role:'error',content:ev.data.message}])}};return()=>ws.close()},[active]);
const send=async()=>{if(!active||!input.trim()||running)return;const m=input;setInput('');setMessages(x=>[...x,{id:crypto.randomUUID(),role:'user',content:m}]);try{await api(`/sessions/${active}/messages`,{method:'POST',body:JSON.stringify({message:m})})}catch(e){setRunning(false);setMessages(x=>[...x,{id:crypto.randomUUID(),role:'error',content:String(e)}])}};
const newChat=async()=>{const a=agents.find(x=>x.installed);if(!a)return alert('请先安装/配置 Agent');const s=await api('/sessions',{method:'POST',body:JSON.stringify({agent_id:a.id,workspace:'/workspaces',title:'New Chat'})});setSessions(x=>[s,...x]);setActive(s.id);setMessages([])};
const install=async(id:string)=>{setInstalling(id);try{await api(`/agents/${id}/install`,{method:'POST'});setTimeout(()=>api('/agent-catalog').then(setAgents),1500)}finally{setInstalling(undefined)}};
const activeSession=useMemo(()=>sessions.find(x=>x.id===active),[sessions,active]);
return <div className="app"><aside><header>Agent Web</header><button onClick={newChat}><Plus size={16}/> New Chat</button><h4>Sessions</h4>{sessions.map(s=><div className={'session '+(active===s.id?'active':'')}onClick={()=>setActive(s.id)}key={s.id}><MessageCircle size={15}/>{s.title}<small>{s.status}</small></div>)}<div className="bottom"><button onClick={()=>setCatalog(!catalog)}><Settings size={16}/> Agents</button></div></aside><main><div className="top"><span>{activeSession?.title||'Select a session'}</span>{active&&running&&<button onClick={()=>api(`/sessions/${active}/interrupt`,{method:'POST'}).then(()=>setRunning(false))}><Square size={14}/> Stop</button>}</div><section className="chat">{messages.map(m=><div key={m.id} className={'message '+m.role}><div className="role">{m.role==='user'?'You':m.role==='assistant'?'Agent':'Error'}</div><pre>{m.content}</pre></div>)}</section><div className="composer"><textarea value={input}disabled={!active||running}onChange={e=>setInput(e.target.value)}onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}placeholder={running?'Agent is working...':'Ask your agent...'}/><button disabled={!active||running||!input.trim()}onClick={send}><SendIcon size={16}/> Send</button></div></main>{catalog&&<aside className="right"><h3>Agents</h3>{agents.map(a=><div className="agent"key={a.id}><b>{a.name}</b><p>{a.description}</p><small>{a.installed?'Installed':'Not Installed'} {a.requirements.length&&'· '+a.requirements.join(', ')}</small>{!a.installed&&<button disabled={installing===a.id}onClick={()=>install(a.id)}>{installing===a.id?'Installing...':'Install'}</button>}</div>)}</aside>}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
